### ISSUE TITLE
exports to file with no extension

### ISSUE THREAD

**Issue by thomhall** [marvingreenberg/FaceSVG#14]
the file exported cannot be opened - when I rename to an SVG file, it doesn't recognize it as the image file I made. What am I doing wrong?

**Comment by thomhall** [comment]
![image](https://user-images.githubusercontent.com/17531731/38180248-5bee577e-35e8-11e8-8f4b-f4bd82102140.png)
seems to alternate between this and the file with no extension

**Comment by marvingreenberg** [comment]
The issue with "reference to deleted entity" is the same as the issue #7 - I have a fix for this just haven't bothered to make a release.  I don't really understand what you mean about renaming the file as an SVG.  When you save the file you should save it in a file name with the .svg suffix.  If a file is getting created, then it should have svg data in it, and why you would be unable to open it is some issue between you and Windows.  Windows can be a PITA. since there really aren't any tools around that let you JUST LOOK at a file.  Try opening with Wordpad (by saying open any file *.* on the open dialog).

**Comment by thomhall** [comment]
@marvingreenberg is there a workaround to the deleted entity issue? I created a simple block, deleted nothing, but still got the same issue.  Is it caching something from the previous operation?

**Comment by marvingreenberg** [comment]
I've put up a new release that has the refactored code to address this issue.  This should not have been happening with a simple rectangular face but you don't describe the process you used - is this a new Sketchup model with just a single block, or was this geometry you added to the existing model.

In any case, try the new release.  IF you are still experiencing the exception "reference to Deleted Entity" please reopen issue #7 and describe what your observe and attach the model (in a zipfile) to the issue.

If you are still experiencing the "file with no extension" issue, please reopen THIS case, and attach screen shots showing the "Save dialog" when you save the file as well as the windows file exploring showing the created file.  In addition, attach the created file packaged in a zip file, if possible.
