### ISSUE TITLE
Having Trouble Exporting To SVG Layout

### ISSUE THREAD

**Issue by DEvangelisto** [marvingreenberg/FaceSVG#24]
Hey Marvin,
I'm trying to export the face of my Sketchup model to a SVG file using your FaceSVG extension, but I keep getting an error.  The closest I can get is the overall outline of the face, but none of the holes in the face transfer to the SVG layout.  I'm pretty new to Sketchup, so I'm thinking it's probably something simple that I'm doing (or not doing).  Are you able to take a look at my Sketchup file and provide me with some insight as to what the issue is and how I can resolve it?
Thanks in advance for any help with this and thanks so much for creating an awesome plugin to help Woodworkers like me.
-David Evangelisto
David.Evangelisto@gmail.com

[SysInsert Router Bit Tray with Holes FINAL1.zip](https://github.com/marvingreenberg/FaceSVG/files/2719780/SysInsert.Router.Bit.Tray.with.Holes.FINAL1.zip)

**Comment by marvingreenberg** [comment]
As soon as I opened it, I recognized that model.  Someone else was having a problem with the systainer model earlier.   I'll see what the issue was.  I think it was some arcs with too small a radius or something.

**Comment by marvingreenberg** [comment]
The issue (Issue #7) was fixed.  I did the export and it worked for me but took MANY minutes.   I'm guessing maybe the issue if memory or something.  I'm on a Mac which might be better than Windows for memory management... 

That's a lot of holes, I don't envy you cutting all those with the shaper...  Do you really have 1000 1/6" router bits?  Anyways, this .zip has the svg and a screenshot of the svg layout in sketchup. 

[systainer.zip](https://github.com/marvingreenberg/FaceSVG/files/2722558/systainer.zip)

I'm going to call this closed.  BTW, I'm using FaceSVG version 2.2.2 (Issue #7 was fixed in 2.2.0)
