### ISSUE TITLE
How do you get this to work?

### ISSUE THREAD

**Issue by Sensebellum** [marvingreenberg/FaceSVG#30]
I love this plugin but it only works 1% of the time.

Maybe I am using it wrong. I read the documentation multiple time. I can't even get a basic circle to "Layout"... see attached file...

https://drive.google.com/open?id=1Pkwg07Bj894Eh6OsSqvdJYV1VTD3uL7c

Or, if it takes more programming time for you to make this work right I am happy to donate.

Bottom line is that this plugin is the ONLY way to get SVG files out of SU for use in CNC applications so we need to dial this in. I am sure everyone would benefit from a working plugin or better documentation.

**Comment by Sensebellum** [comment]
For instance after 20+ tries I finally was able to get one piece of geometry to actually "Layout". I just kept zeroing out the settings and trying again.

If after 20 times, no changes to the geometry, it does finally work, I am wondering if this is a bug? Else it should work first try or never?

I have found that "Reset Layout" usually helps this along but not always.

Like I said I love this plugin but we really need to get it working right!

Thank you,

**Comment by marvingreenberg** [comment]
Unfortunately, the last Sketchup I have a paid license for is 2017, and I cannot open your model.  I'm sorry it isn't working for you.  Trimble has made it much more difficult for me to develop the plugin.  I know this isn't a helpful suggestion, but if you can duplicate the problem in an older version of Sketchup (like Sketchup Make 2017, https://help.sketchup.com/en/downloading-older-versions) I could try to look at it.

**Comment by Sensebellum** [comment]
Wow that is a bummer! Lets see what we can do.

I mean do you have any intention of developing this further? It seems like a crucial plugin but one in which you are not dedicated to?

Here is a 17 Version. Once again the plugin works sometimes but not every time. Some faces always "Layout". Some only "Layout" after repeated tries.

https://drive.google.com/open?id=1sjC_Bpgr6wjwv1hvIQrSzv_T1oTsepiE 

Thank you for taking a look!

**Comment by marvingreenberg** [comment]
I downloaded your model and output some SVG from it.  It seemed to work fine.  I use the plugin "regularly" maybe every few weeks or months or so, and I'm committed to improving it, but I wouldn't hold my breath.  I don't know if there are new issues from SU 2019.  There are definitely some issues I know about and some that I don't, probably.  I spent a week a few months back to improve some things but, like everything, that is on the back burner now, 70% complete.  I alternate between projects making actual things, remodeling my house, several software projects (See https://sojoinery.appspot.com/ another currently orphaned project) and everything else - kids and family, work, sports.  

Anyway, I made this movie https://youtu.be/Q92CXsSlD3E - showing how I made a bunch of SVG from your model.  You don't need to rearrange the "laid out" SVGs as I show, I just wanted to show that you can.  The attached zip file has the SVG I generated.  You generally select each face and "lay them out" individually.

[17.zip](https://github.com/marvingreenberg/FaceSVG/files/3633137/17.zip)

I probably need to make a chat room or something, since discussions like this don't really belong in issues...

**Comment by marvingreenberg** [comment]
I think this was all resolved.
